### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by AkihiroSuda** [leesper/go_rng#2]
Hello, could you please clarify the license?

**Comment by leesper** [comment]
Ok, this is Apache Licensed, thank you for your reminding!

**Comment by AkihiroSuda** [comment]
Thanks!

**Comment by leesper** [comment]
ありがとうございます ^_^

**Comment by AkihiroSuda** [comment]
谢谢您！明天（或是后天..）我打算发起关于
狄利克雷(dirichlet)分布的pull request!

**Comment by leesper** [comment]
Thank you! HAPPY CHINESE NEW YEAR  ^o^/

**Comment by AkihiroSuda** [comment]
Gong xi fa cai, please review #6. :smile:
